roomlist = [
    {"Room number":"R21.02", "Room name":"Board room"},
    {"Room number":"R21.03", "Room name":"LATAM"},
    {"Room number":"R21.05", "Room name":"Heinz"},
    {"Room number":"R21.06", "Room name":"De Ruijter"},
    {"Room number":"R21.08", "Room name":"Asia"},
    {"Room number":"R21.09", "Room name":"Plasmon"},
    {"Room number":"R21.10", "Room name":"Telepresence"},
    {"Room number":"R21.11", "Room name":"Karvan Cevetam"},
    {"Room number":"R21.14", "Room name":"East"},
    {"Room number":"R21.15", "Room name":"Honig"},
    {"Room number":"R20.02", "Room name":"Lea & Perrins"},
    {"Room number":"R20.03", "Room name":"The Creative Room"},
    {"Room number":"R20.04", "Room name":"Amoy"},
    {"Room number":"R20.05", "Room name":"Seriously good"},
    {"Room number":"R20.06", "Room name":"HP"},
    {"Room number":"R20.07", "Room name":"Daddies"},
    {"Room number":"R20.10", "Room name":"Kraft"},
    {"Room number":"R20.11", "Room name":"bulls-eye"},
    {"Room number":"R20.12", "Room name":"Orlando"},
    {"Room number":"R20.13", "Room name":"Weight Watchers"},
    {"Room number":"R20.16", "Room name":"Farleys"},
    {"Room number":"R20.17", "Room name":"Venz"}
    ]